import React from "react";
import Forms from "@chappy/components/Forms";
import route from "@chappy/utils/route";
import documentTitle from '@chappy/utils/documentTitle';

/**
 * Generates the edit profile component
 * @property {object} user The users model object.
 * @property {object} errors The errors generated by the users model.
 * @property {array} profileImage Array that contains object for currently 
 * selected profile image.
 * @param {InputProps} param0 
 * @returns {JSX.Element} The edit profile view component.
 */
function Edit({user, errors }) {
    documentTitle(`Edit Details for ${user.username}`);

    return (
        <div className="row align-items-center justify-content-center mb-5">
            <div className="col-md-6 bg-light p-3">
                <h1 className="text-center">Edit Details for {user.username}</h1>
                <hr />
                <form className="form" action="" method="post" encType="multipart/form-data">
                    <Forms.CSRFInput />
                    <Forms.DisplayErrors errors={errors}/>
                    <Forms.Input 
                        type="text"
                        label="First Name"
                        name="fname"
                        value={user.fname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Input 
                        type="text"
                        label="Last Name"
                        name="lname"
                        value={user.lname}
                        inputAttrs={{className: 'form-control input-sm'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <Forms.Email 
                        label="Email"
                        name="email"
                        value={user.email}
                        inputAttrs={{className: 'form-control input-sm', placeholder: 'joe@example.com'}}
                        divAttrs={{className: 'form-group mb-3'}}
                    />
                    <div className="col-md-12 text-end">
                        <a href={route('profile')} className="btn btn-default">Cancel</a>
                        <Forms.SubmitTag label={"Submit"} inputAttrs={{className: 'btn btn-primary'}}/>
                    </div>
                </form>
            </div>
        </div>
    );
}

export default Edit;