source "https://rubygems.org"

# Use the GitHub Pages gem, which includes Jekyll
gem "github-pages", group: :jekyll_plugins

# Minima is included with GitHub Pages, so you don't need to specify a version.
gem "minima"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby fixes
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", platforms: [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]
